export const FRIEND = 'FRIEND';
export const REQUESTED = 'REQUESTED';
export const REQUESTING = 'REQUESTING';
export const UNFRIEND = 'UNFRIEND';
export const FROMPROFILE = 'FROMPROFILE';
export const FROMMASTERPROFILE = 'FROMMASTERPROFILE';
